### PR TITLE
Fix panic when Hostname is used

### LINKED ISSUE #69: `v1.1.0` panics when `Hostname` is used rather than `Host` in the oauth flow.
## Description

https://github.com/cli/oauth/pull/63 introduced a new safe parsing function `NewGitHubHost` which ensures that the URL parsing is valid. Consumers of this library can use it in order to pass in `Host` in the `OauthFlow` configuration struct: https://github.com/cli/oauth/blob/afffc8e9e8de901d5ce56684c9bf5e8485830bbc/oauth.go#L68

However, it was possible to provide the deprecated `Hostname` string and both the [device code and oauth flows would do the parsing internally. ](https://github.com/cli/oauth/blob/afffc8e9e8de901d5ce56684c9bf5e8485830bbc/oauth_device.go#L35).

In #63, this parsing was changed to use the new function (which is great) but in doing so, some unintentional variable shadowing happened. Previously, the result of `GitHubHost` was assigned to the `host` variable which was used later on. Now the result of `NewGitHubHost` is assigned to `host, err` via short variable declaration (`:=`). This results in a new `host` variable being declared in the inner scope. Although we set `oa.Host = host`, the rest of the functions still use `host`, which results in a nil pointer deference.

### Reproduction

Use these tests:

```go
package oauth_test

import (
	"testing"

	"github.com/cli/oauth"
)

func TestDeviceFlowHostname(_ *testing.T) {
	flow := &oauth.Flow{
		Hostname: "github.com",
	}

	_, err := flow.DeviceFlow()
	if err != nil {
		panic(err)
	}
}

func TestWebFlowHostname(_ *testing.T) {
	flow := &oauth.Flow{
		Hostname: "github.com",
	}

	_, err := flow.WebAppFlow()
	if err != nil {
		panic(err)
	}
}
```

They will panic on:

```
github.com/cli/oauth.(*Flow).DeviceFlow(0x1400007aeb0)
	/Users/williammartin/workspace/oauth/oauth_device.go:42 +0x188
```

https://github.com/cli/oauth/blob/afffc8e9e8de901d5ce56684c9bf5e8485830bbc/oauth_device.go#L42

```
github.com/cli/oauth.(*Flow).WebAppFlow(0x140001462c0)
	/Users/williammartin/workspace/oauth/oauth_webapp.go:37 +0x16c
```

https://github.com/cli/oauth/blob/afffc8e9e8de901d5ce56684c9bf5e8485830bbc/oauth_webapp.go#L36-L37

Note that these tests aren't otherwise intended to pass (e.g. Device flow will panic for other reasons on an earlier commit), just to demonstrate the issue.

### PR DESCRIPTION
**Pull request by williammartin**
## Description

Fixes #69

### Reviewer Notes

We should backfill some tests for this very untested code but I think it's important that we get a v1.1.1 release out before too many people upgrade.

### CODE REVIEW

File: oauth_device.go [hunk 1]
```diff
@@ -32,11 +32,11 @@ func (oa *Flow) DeviceFlow() (*api.AccessToken, error) {
...
 	host := oa.Host
 	if host == nil {
-		host, err := NewGitHubHost("https://" + oa.Hostname)
+		parsedHost, err := NewGitHubHost("https://" + oa.Hostname)
 		if err != nil {
-			return nil, fmt.Errorf("error parsing the hostname '%s': %w", host, err)
+			return nil, fmt.Errorf("error parsing the hostname '%s': %w", oa.Hostname, err)
 		}
-		oa.Host = host
+		host = parsedHost
```
Comment (nodo) [inline oauth_device.go:39]: shouldn't you also change `os.Host`? that's potentially a difference in the new logic.

Comment (williammartin) [reply oauth_device.go:39]: Good question. No. This was unnecessarily introduced in https://github.com/cli/oauth/pull/63/files#diff-27a48aeb100977fb1eed81f2617982a9a80846825a1be07665a0a8163968d0ceR39

It's never used again. I don't think we should be mutating the struct that the user provided either.
